version: '3'
services:
  db:
    image: sqlite3
    volumes:
      - ./tmp/db:/var/lib/sqlite3/data
  web:
    build: .
    container_name: onebitmessenger
    volumes:
      - .:/onebitmessenger
    ports:
      - '3000:3000'
    depends_on:
      - db
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
